services:

  mongo:
    image: mongo:latest
    env_file:
      - ./dev.env    
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - testdb_data:/usr/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    env_file:
      - ./dev.env    
    depends_on:
        - mongo
    ports:
        - 8081:8081
    command: ["bash", "-c", "sleep 10 && /docker-entrypoint.sh"]   

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/app
    environment:
      - TEMDB_ENV=dev
    depends_on:
      - mongo

  docs:
      build:
        context: .
        dockerfile: Dockerfile.docs
      ports:
        - "8001:8000"
      volumes:
        - ./docs:/docs_app/docs
        - ./mkdocs.yml:/docs_app/mkdocs.yml
        # - ./generate_schema_diagram.py:/docs_app/generate_schema_diagram.py
        # - ./temdb:/docs_app/temdb
      restart: unless-stopped

  
volumes:
  testdb_data:
