[project]
name = "TEMdb"
version = "0.1.0"
authors = [
    { name="Derrick Brittain", email="derrickb@alleninstitute.org" }
]
dependencies = [
    "fastapi",
    "uvicorn",
    "beanie",
    "pydantic",
    "pydantic-settings",
    "jinja2",
    "python-multipart",
    "uvicorn-worker"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-asyncio",
    "faker",
    "mongomock-motor"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["temdb"]